### ISSUE TITLE
Please add parameters to getPagelist

### ISSUE THREAD

**Issue by chang-zhao** [kynan/dokuwikixmlrpc#11]
Requesting `dw.pagelist(':')` gives all the pages, maybe many thousands. Users may be interested in limiting the depth of search:

```dw.pagelist(':', {'depth': 1})```

but that gives

```TypeError: DokuWikiClient.pagelist() takes 2 positional arguments but 3 were given```

It's reasonable to add the second parameter here:

```
    def pagelist(self, namespace):
        """Lists all pages within a given namespace."""
        return self._xmlrpc.dokuwiki.getPagelist(namespace, {})
```

Kind of

```
    def pagelist(self, namespace, opts = {'depth': 0, 'hash': False, 'skipacl': False}):
        """Lists all pages within a given namespace."""
        return self._xmlrpc.dokuwiki.getPagelist(namespace, opts)
```

**Comment by kynan** [comment]
This has been addressed by #12 , please reopen if you think there's anything left to do.
