### ISSUE TITLE
Relicense as MIT

### ISSUE THREAD

**Issue by kynan** [kynan/dokuwikixmlrpc#6]
I have approval from @chimeric to relicense under a more liberal MIT license. Any objections @foosel @kaie @yvesf @meteopascal?

**Comment by foosel** [comment]
None at all

**Comment by bbsteam** [comment]
Hello Florian,

No objection at all.
Thanks for taking the project over.

Pascal

**Comment by kaie** [comment]
No objections

**Comment by yvesf** [comment]
No objections

**Comment by kynan** [comment]
Thanks for confirming, I'll go ahead then!
