### ISSUE TITLE
Basic auth case doesn't add the script path. 

### ISSUE THREAD

**Issue by todmorrison** [kynan/dokuwikixmlrpc#9]
This looks wrong to me:

        if not self._http_basic_auth:
            url = ''.join([self._url, script, '?',
                           urlencode({'u': self._user, 'p': self._passwd})])
        else:
            proto, url = self._url.split('://')
            url = proto + '://' + self._user + ':' + self._passwd + '@' + url

In the "not" basic auth case the script path is added to the base url, while in the "use" basic auth case it is not (and, hence, the base url need to include the full script path).

**Comment by kynan** [comment]
Thanks for reporting this. Looks like a clear oversight to me. Note that I didn't write most of the code, I only did the Python 3 conversion and maintain the library since.

FWIW, when I try HTTP basic auth I get a 401 (same as in #8), so I'm not sure if it's even (still) supported by DokuWiki?

**Comment by todmorrison** [comment]
Hi,

I've got a self-signed cert, so I had to hacked it a bit on the plugin side (I left the python module as is). Here's my full diff:

``diff --git a/plugin/dokuvimki.py b/plugin/dokuvimki.py
index ad16091..d94a195 100644
--- a/plugin/dokuvimki.py
+++ b/plugin/dokuvimki.py
@@ -8,6 +8,19 @@ import re
 import vim
 import time

+import ssl
+
+# my addition
+try:
+    _create_unverified_https_context = ssl._create_unverified_context
+except AttributeError:
+    # Legacy Python that doesn't verify HTTPS certificates by default
+    pass
+else:
+    # Handle target environment that doesn't support HTTPS verification
+    ssl._create_default_https_context = _create_unverified_https_context
+# end my addition
+
 __version__ = '2020.5.23'
 __author__ = 'Michael Klier <chi@chimeric.de>'
 __license__ = 'MIT'
@@ -106,7 +119,7 @@ class DokuVimKi:
             return False

         try:
-            self.xmlrpc = dokuwikixmlrpc.DokuWikiClient(self.dw_url, self.dw_user, self.dw_pass)
+            self.xmlrpc = dokuwikixmlrpc.DokuWikiClient(self.dw_url, self.dw_user, self.dw_pass, True)
             print('Connection to ' + vim.eval('g:DokuVimKi_URL') + ' established!', file=sys.stdout)
             return True
         except dokuwikixmlrpc.DokuWikiXMLRPCError as err:
@@ -937,4 +950,4 @@ class Buffer:

         if type == 'nowrite':
             self.diff = {}
-            vim.command("setlocal statusline=%{'[wp]\ " + self.name + "'}\ %r\ [%c,%l][%p%%]")
\ No newline at end of file
+            vim.command("setlocal statusline=%{'[wp]\ " + self.name + "'}\ %r\ [%c,%l][%p%%]")``

My config is:

``  let g:DokuVimKi_USER = 'myusername'
  let g:DokuVimKi_PASS = 'mypassword!'
  let g:DokuVimKi_URL  = 'https://myhost/dokuwiki/lib/exe/xmlrpc.php'``

**Comment by kynan** [comment]
As of Python 3.5, `ServerProxy` [supports a `context` parameter](https://docs.python.org/3/library/xmlrpc.client.html#xmlrpc.client.ServerProxy). If that was exposed via the `DokuWikiClient` controller you could call `DokuWikiClient(..., context=ssl.SSLContext())` (which defaults to `verify_mode=CERT_NONE` afaict, so that's probably what you want).

Would this address your use case?

**Comment by todmorrison** [comment]
Hi,

Yes, you're a step ahead of me :)

I was going to make a "feature request" for this (here or for the vim plugin) to do just that after this url "bug" was fixed (since the url issue seems like a more general "bug" and the SSL context issue is really just a feature to deal with the fact I haven't found where HomeBrew python looks for its trusted certs yet).

**Comment by kynan** [comment]
OK. I've pushed 2 commits to fix both. Do you want to test with the current master before I tag a new release?

**Comment by todmorrison** [comment]
The script path change fixes that issue, but SSL validation still needs my original hack.

`from dokuwikixmlrpc import DokuWikiClient
import ssl
import sys

username = 'username'
password = 'password'
wikiroot = 'https://host/dokuwikiroot'

if len(sys.argv[1]) > 0:
    test = sys.argv[1]
else:
    test = '3'

if test == '1':
    print('Case 1')
    client = DokuWikiClient(wikiroot, username, password, True)
    print(client.page('home'))

elif test == '2':
    print('Case 2')
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    client = DokuWikiClient(wikiroot, username, password, True, context=ctx)
    print(client.page('home'))

elif test == '3':
    print('Case 3')
    try:
        _create_unverified_https_context = ssl._create_unverified_context
    except AttributeError:
        # Legacy Python that doesn't verify HTTPS certificates by default
        pass
    else:
        # Handle target environment that doesn't support HTTPS verification
        ssl._create_default_https_context = _create_unverified_https_context

    client = DokuWikiClient(wikiroot, username, password, True)
    print(client.page('home'))`

Trying this, only test "3" works. The other two both fail trying to validate the cert.

**Comment by kynan** [comment]
Thanks, that's useful to know. I don't have a server with a self-signed cert available to test. If you like, you could create a dummy account on your wiki and email me the credentials and URL.

Does the following test case also fail validating the cert?
```
client = DokuWikiClient(wikiroot, username, password, True, context=ssl.SSLContext())
print(client.page('home'))
```

**Comment by kynan** [comment]
On a separate note, I'm a little puzzled why HTTP Basic Auth doesn't seem to work for me. I get a 401 running the following test. Does that work for you?
```python
from xmlrpc.client import ServerProxy
c = ServerProxy('https://username:password@wikiroot/lib/exe/xmlrpc.php')
print(c.dokuwiki.getVersion())
```

**Comment by todmorrison** [comment]
Yep (with the SSL hack), it prints:

Release 2020-07-29 "Hogfather"

**Comment by todmorrison** [comment]
Well, I've not yet succeeded in getting any ssl.context configurations to make it through the xmlrpc layer. However, as a consequence of all my investigations along those line I did finally trip over what I needed to do to add my CA cert to the openssl trust that the HomeBrew installed python uses, so now my cert validates. For the record, it looks like the xmlrpc library/module does everything in its power to prevent you from overriding ssl context parameters and my initial hack is the only way to prevent validation.

Anyway, with the script path fix and making my cert trusted at the python "system" level (it was already trusted by the OS) I'm up and running with a non-hackish config. My dokuwiki instance is not routable from the Internet, so I can't make it available to you, but I'm happy to answer any questions about my config that might reveal why basic auth works for me an not for you.

**Comment by kynan** [comment]
Great news on getting your cert working!

Do you want to file a feature request against https://github.com/kynan/dokuvimki to add a config option for enabling basic auth?

I'll need to experiment more on the basic auth issue. Thanks for offering to help :)

**Comment by todmorrison** [comment]
"Do you want to file a feature request against https://github.com/kynan/dokuvimki to add a config option for enabling basic auth?"

That was my my next step :)

Thanks for your help on this one and thanks for writing this code.

Cheers,
Tod

**Comment by kynan** [comment]
I've done some testing with the [Bitnami Docker image](https://hub.docker.com/r/bitnami/dokuwiki/) and HTTP basic auth works just fine. I suspect the host where I have my wiki strips basic auth headers.

I'll close this, as the actual issue is fixed.
